### ISSUE TITLE
Error on main dashboard

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-webui#11]
When visiting the homepage (main dashboard) page, an error is thrown. See screenshot below:

![screenshot from 2016-05-26 08 27 30](https://cloud.githubusercontent.com/assets/231601/15561083/91e5f6a6-231c-11e6-89b5-b0245f343618.png)

Related traceback is here:

```pytb
127.0.0.1 - - [26/May/2016 08:27:03] "GET /dashboard HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/iromli/.virtualenv/gluu-webui/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/work/gluu/gluu-webui/gluuwebui/views.py", line 319, in dashboard_data
    if node['state'] == 'SUCCESS':
KeyError: 'state'

```

**Comment by tecoholic** [comment]
![Updated Dashboard](https://cloud.githubusercontent.com/assets/383862/15567933/d8f80c80-2346-11e6-9b78-1d5e18cb3fc6.png)

**Comment by iromli** [comment]
Beautiful. Thanks @tecoholic

**Comment by tecoholic** [comment]
@iromli Thank you for all the reports Isman 👍
